{% set name = "pyworms" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/iobis/pyworms/archive/{{ version }}.tar.gz
  sha256: 7b671d88995508187d56cd228a95d8741bf8eb5f6427201e189073a563bd14b7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - backports.functools_lru_cache
    - requests

test:
  imports:
    - pyworms

about:
  home: https://github.com/iobis/pyworms
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Python client for the WoRMS REST service

extra:
  recipe-maintainers:
    - ocefpaf
