{% set name = "pyworms" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/iobis/pyworms/archive/{{ version }}.tar.gz
  sha256: f066f87f9199ae5c6a7a9964848c531d358d3514fd5bc15f17392f094d8bc6a7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - backports.functools_lru_cache
    - requests

test:
  imports:
    - pyworms
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/iobis/pyworms
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Python client for the WoRMS REST service

extra:
  recipe-maintainers:
    - ocefpaf
